server:
  port: 8888
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/elsamuell/config-server
          username: username
          password: password
          default-label: main
  application:
    name: config-service
  security:
    user:
      name: config
      password: config

logging:
  level:
    com.netflix.discovery: 'OFF'
    org.springframework.cloud: 'DEBUG'

discovery:
  eureka-hostname: http://eureka:eureka@localhost:8761/eureka
  client-hostname: config-service

eureka:
  instance:
    hostname: ${discovery.client-hostname}
    prefer-ip-address: true
    instance-id: ${eureka.instance.hostname}:${server.port}
    leaseRenewalIntervalInSeconds: 10
  client:
    register-with-eureka: true
    fetch-registry: true
    registryFetchIntervalSeconds: 5
    service-url:
      defaultZone: ${discovery.eureka-hostname}